import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/include/Sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
      >
        <main className="main wrap">
          <div className="grid place-content-center w-screen h-screen overflow-y-auto overflow-x-hidden">
            <div className="flex items-center w-[1268px] max-w-full h-[674px] max-h-screen m-auto">
              <div className="w-[480px]">
                <Sidebar />
              </div>
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
